### ISSUE TITLE
merge_bed.py chokes on find_circ2 output

### ISSUE THREAD

**Issue by mschilli87** [rajewsky-lab/find_circ2#9]
Trying to combine two runs analyzed with the latest `find_circ2` by

```sh
merge_bed.py \
  --format=2 \
  <(zcat sample1.circ_splice_sites.bed.gz) \
  <(zcat sample2.circ_splice_sites.bed.gz) \
| pigz \
  --best \
> merged.circ_splice_sites.bed.gz
```

I get

```
circ_splice_sites
Traceback (most recent call last):
  File "merge_bed.py", line 176, in <module>
    cols = [comstr] + consensus_cols(lines,comb)
  File "merge_bed.py", line 138, in consensus_cols
    parts.append(str(col_map[i](column)))
  File "merge_bed.py", line 123, in <lambda>
    9 : lambda values : array(values,dtype=int).sum(), # sum ov_linear_A
ValueError: invalid literal for long() with base 10: '0.5'
```

@marvin-jens: I'm willing to fix it myself but I'll need some directions. ;)

**Comment by mschilli87** [comment]
@retaj: Maybe you can comment how you do these kind of things? `ciRcus`/`BED6` only/Not at all?

**Comment by marvin-jens** [comment]
Hi Marcel, didn't see the notification as MDC email is checked only intermittently. I'd prefer if you guys would move this functionality to ciRcus. Table merging is definitely sth that's handled more cleanly in R. The merge_bed.py is a bit hacky, to say the least, and I wouldn't be sad to see it go away. Thanks for inquiring.

**Comment by mschilli87** [comment]
Allright, marked as [wontfix].

Reading `find_circ2` output is supported in [`ciRcus`](https://github.com/BIMSBbioinfo/ciRcus) since about a week (https://github.com/BIMSBbioinfo/ciRcus/commit/c8ef7f55d1c2003b9d9c7691c9542af999ecb2b7).

I'll leave this issue open until we have

- [ ] implemented proper flag merging in `ciRcus`,
- [ ] updated the `find_circ2` `README` accordingly &
- [ ] deleted `merge_bed.py` from this repository.

PS: It is possible to [update your email on github](https://help.github.com/articles/changing-your-primary-email-address/). ;)
PPS: Make sure to keep the old one (as non-primary) to not loose association of old commits to you profile.

**Comment by marvin-jens** [comment]
Thanks Marcel. I already changed email settings yesterday, exactly as you 
propose.
